shellEmulator: true

trustPolicy: no-downgrade
onlyBuiltDependencies:
  - ' '
  - '-'
  - ;
  - e
  - esbuild
  - g
  - h
  - i
  - k
  - l
  - m
  - msw
  - o
  - p
  - s
  - simple-git-hooks
  - t
  - unrs-resolver
