name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master # Corrected to 'master' based on your repo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false # We'll run pnpm install explicitly in the next step

      # Setup Node.js with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Recommended Node.js LTS version. Adjust if your project needs a different one.
          cache: "pnpm" # Enables caching for pnpm dependencies

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use --frozen-lockfile for CI/CD for reproducible builds

      # Build the project using pnpm
      - name: Build project
        run: pnpm run build # Replaces 'npm run build'

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODO_DAILY_D50DD }}
          channelId: live
          projectId: todo-daily-d50dd
